# docker-compose.yml
version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: ai_assistant_db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # <-- ADD THIS LINE

  redis:
    image: redis:7
    container_name: ai_assistant_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: